export interface SizeVariant {
  size: string
  price: number
  originalPrice: number | null
}

export interface Product {
  id: string
  name: string
  slug: string
  price: number
  originalPrice: number | null
  rating: number
  reviews: number
  image: string
  images: string[]
  badge: string
  category: string
  weight: string
  sizes: SizeVariant[]
  description: string
  ingredients: string
  shelfLife: string
  isVeg: boolean
  isBestseller: boolean
  isNew: boolean
}

export const products: Product[] = [
  // =====================
  // SWEETS (30 items)
  // =====================
  {
    id: "s1",
    name: "Ariselu",
    slug: "ariselu",
    price: 160,
    originalPrice: null,
    rating: 4.8,
    reviews: 110,
    image: "/images/product-ariselu.jpg",
    images: ["/images/product-ariselu.jpg", "/images/category-sweets.jpg"],
    badge: "Traditional",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Traditional Andhra Ariselu made with rice flour, jaggery, and sesame seeds. Crispy on the outside, soft on the inside, prepared using age-old recipes passed down through generations.",
    ingredients: "Rice flour, Jaggery, Sesame seeds, Cardamom, Ghee",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s2",
    name: "Avisaginjala Laddu",
    slug: "avisaginjala-laddu",
    price: 300,
    originalPrice: null,
    rating: 4.9,
    reviews: 78,
    image: "/images/product-avisaginjala-laddu.jpg",
    images: ["/images/product-avisaginjala-laddu.jpg", "/images/category-sweets.jpg"],
    badge: "Premium",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 300, originalPrice: null },
      { size: "500g", price: 570, originalPrice: null },
      { size: "1kg", price: 1080, originalPrice: null },
    ],
    description: "Protein-rich Avisaginjala (Flax Seed) Laddu made with flax seeds, jaggery, and dry fruits. A healthy, power-packed sweet that is highly nutritious and delicious.",
    ingredients: "Flax seeds, Jaggery, Dry fruits, Ghee, Cardamom",
    shelfLife: "20 days",
    isVeg: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: "s3",
    name: "Badusha",
    slug: "badusha",
    price: 230,
    originalPrice: null,
    rating: 4.7,
    reviews: 92,
    image: "/images/product-badusha.jpg",
    images: ["/images/product-badusha.jpg", "/images/category-sweets.jpg"],
    badge: "Popular",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 230, originalPrice: null },
      { size: "500g", price: 437, originalPrice: null },
      { size: "1kg", price: 828, originalPrice: null },
    ],
    description: "Soft, flaky Badusha soaked in sugar syrup. A beloved North Indian-style sweet that melts in your mouth. Each piece is hand-shaped and deep-fried to golden perfection.",
    ingredients: "Maida, Sugar, Ghee, Yogurt, Cardamom, Baking soda",
    shelfLife: "15 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s4",
    name: "Bandar Laddu",
    slug: "bandar-laddu",
    price: 200,
    originalPrice: null,
    rating: 4.8,
    reviews: 104,
    image: "/images/product-bandar-laddu.jpg",
    images: ["/images/product-bandar-laddu.jpg", "/images/category-sweets.jpg"],
    badge: "Signature",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 200, originalPrice: null },
      { size: "500g", price: 380, originalPrice: null },
      { size: "1kg", price: 720, originalPrice: null },
    ],
    description: "Famous Bandar Laddu (Machilipatnam style) made with senaga pindi (besan), sugar, ghee, and cardamom. The iconic Andhra sweet known for its rich flavor and crumbly texture.",
    ingredients: "Besan, Sugar, Ghee, Cardamom, Cashews",
    shelfLife: "20 days",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "s5",
    name: "Bellam Gavvalu",
    slug: "bellam-gavvalu",
    price: 180,
    originalPrice: null,
    rating: 4.7,
    reviews: 88,
    image: "/images/product-bellam-gavvalu.jpg",
    images: ["/images/product-bellam-gavvalu.jpg", "/images/category-sweets.jpg"],
    badge: "Festive",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 180, originalPrice: null },
      { size: "500g", price: 342, originalPrice: null },
      { size: "1kg", price: 648, originalPrice: null },
    ],
    description: "Shell-shaped Bellam Gavvalu made with rice flour and jaggery (bellam). A traditional Andhra festive sweet that is crunchy on the outside and sweet inside. A Sankranti must-have.",
    ingredients: "Rice flour, Jaggery, Ghee, Sesame seeds, Cardamom",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s6",
    name: "Bobbatlu",
    slug: "bobbatlu",
    price: 250,
    originalPrice: null,
    rating: 4.8,
    reviews: 167,
    image: "/images/product-bobbatlu.jpg",
    images: ["/images/product-bobbatlu.jpg", "/images/category-sweets.jpg"],
    badge: "Festive",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 250, originalPrice: null },
      { size: "500g", price: 475, originalPrice: null },
      { size: "1kg", price: 900, originalPrice: null },
    ],
    description: "Traditional Bobbatlu (Puran Poli) made with chana dal and jaggery filling, wrapped in a soft dough and cooked on a griddle with ghee. A festive favorite that celebrates Telugu traditions.",
    ingredients: "Chana Dal, Jaggery, Maida, Ghee, Cardamom, Nutmeg",
    shelfLife: "5 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s7",
    name: "Boondi Laddu",
    slug: "boondi-laddu",
    price: 330,
    originalPrice: null,
    rating: 4.9,
    reviews: 201,
    image: "/images/product-boondiladdu.jpg",
    images: ["/images/product-boondiladdu.jpg", "/images/category-sweets.jpg"],
    badge: "Bestseller",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 330, originalPrice: null },
      { size: "500g", price: 627, originalPrice: null },
      { size: "1kg", price: 1188, originalPrice: null },
    ],
    description: "Soft and fragrant Boondi Laddus made with chickpea flour, sugar syrup, ghee, and flavored with cardamom and saffron. Each laddu is hand-rolled to perfection.",
    ingredients: "Chickpea flour, Sugar, Ghee, Cardamom, Saffron, Cashews, Raisins",
    shelfLife: "15 days",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "s8",
    name: "Bundi Patti",
    slug: "bundi-patti",
    price: 230,
    originalPrice: null,
    rating: 4.7,
    reviews: 65,
    image: "/images/product-bundi-patti.jpg",
    images: ["/images/product-bundi-patti.jpg", "/images/category-sweets.jpg"],
    badge: "Classic",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 230, originalPrice: null },
      { size: "500g", price: 437, originalPrice: null },
      { size: "1kg", price: 828, originalPrice: null },
    ],
    description: "Flat, rectangular Bundi Patti made with fine boondi soaked in sugar syrup, pressed and set. A layered, chewy delight with the sweetness of sugar and aroma of cardamom.",
    ingredients: "Besan, Sugar, Ghee, Cardamom, Cashews",
    shelfLife: "20 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s9",
    name: "Chalimidi",
    slug: "chalimidi",
    price: 180,
    originalPrice: null,
    rating: 4.6,
    reviews: 72,
    image: "/images/product-chalimidi.jpg",
    images: ["/images/product-chalimidi.jpg", "/images/category-sweets.jpg"],
    badge: "Traditional",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 180, originalPrice: null },
      { size: "500g", price: 342, originalPrice: null },
      { size: "1kg", price: 648, originalPrice: null },
    ],
    description: "Traditional Chalimidi made with rice flour, jaggery, and ghee. A wholesome Andhra sweet that is offered during festivals and pujas. Simple yet deeply satisfying.",
    ingredients: "Rice flour, Jaggery, Ghee, Cardamom, Coconut",
    shelfLife: "10 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s10",
    name: "Dry Fruit Laddu",
    slug: "dry-fruit-laddu",
    price: 420,
    originalPrice: null,
    rating: 4.9,
    reviews: 134,
    image: "/images/product-dry-fruit-laddu.jpg",
    images: ["/images/product-dry-fruit-laddu.jpg", "/images/category-sweets.jpg"],
    badge: "Premium",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 420, originalPrice: null },
      { size: "500g", price: 798, originalPrice: null },
      { size: "1kg", price: 1512, originalPrice: null },
    ],
    description: "Luxurious Dry Fruit Laddu loaded with almonds, cashews, pistachios, dates, and figs, bound with ghee and honey. A protein-rich, healthy sweet perfect for gifting.",
    ingredients: "Almonds, Cashews, Pistachios, Dates, Figs, Ghee, Honey, Cardamom",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "s11",
    name: "Gorumitilu",
    slug: "gorumitilu",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 58,
    image: "/images/product-gorumitilu.jpg",
    images: ["/images/product-gorumitilu.jpg", "/images/category-sweets.jpg"],
    badge: "Classic",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Crispy and sweet Gorumitilu made with rice flour and sugar. A traditional Telugu snack-sweet that is perfect for tea time and festivals.",
    ingredients: "Rice flour, Sugar, Ghee, Sesame seeds, Cardamom",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s12",
    name: "Gulab Jamun",
    slug: "gulab-jamun",
    price: 325,
    originalPrice: null,
    rating: 4.9,
    reviews: 178,
    image: "/images/product-gulab-jamun.jpg",
    images: ["/images/product-gulab-jamun.jpg", "/images/category-sweets.jpg"],
    badge: "Popular",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 325, originalPrice: null },
      { size: "500g", price: 617, originalPrice: null },
      { size: "1kg", price: 1170, originalPrice: null },
    ],
    description: "Soft, melt-in-your-mouth Gulab Jamun soaked in fragrant rose and cardamom sugar syrup. Made with khoya and deep-fried to a perfect golden brown.",
    ingredients: "Khoya, Maida, Sugar, Rose water, Cardamom, Ghee",
    shelfLife: "10 days",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "s13",
    name: "Gulabi Puvvulu",
    slug: "gulabi-puvvulu",
    price: 150,
    originalPrice: null,
    rating: 4.7,
    reviews: 62,
    image: "/images/product-gulabi-puvvulu.jpg",
    images: ["/images/product-gulabi-puvvulu.jpg", "/images/category-sweets.jpg"],
    badge: "Festive",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 150, originalPrice: null },
      { size: "500g", price: 285, originalPrice: null },
      { size: "1kg", price: 540, originalPrice: null },
    ],
    description: "Rose-shaped crispy sweets (Gulabi Puvvulu) made with rice flour and sugar syrup. Beautiful flower-shaped festive treats that are as delightful to look at as they are to eat.",
    ingredients: "Rice flour, Sugar, Ghee, Cardamom, Food color",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s14",
    name: "Kala Jamun",
    slug: "kala-jamun",
    price: 325,
    originalPrice: null,
    rating: 4.8,
    reviews: 95,
    image: "/images/product-kala-jamun.jpg",
    images: ["/images/product-kala-jamun.jpg", "/images/category-sweets.jpg"],
    badge: "Premium",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 325, originalPrice: null },
      { size: "500g", price: 617, originalPrice: null },
      { size: "1kg", price: 1170, originalPrice: null },
    ],
    description: "Dark, rich Kala Jamun - the deeper, more caramelized version of Gulab Jamun. Fried longer for a darker color and richer flavor, soaked in aromatic sugar syrup.",
    ingredients: "Khoya, Maida, Sugar, Cardamom, Rose water, Ghee",
    shelfLife: "10 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s15",
    name: "Kobbari Vundalu",
    slug: "kobbari-vundalu",
    price: 180,
    originalPrice: null,
    rating: 4.7,
    reviews: 73,
    image: "/images/product-kobbari-vundalu.jpg",
    images: ["/images/product-kobbari-vundalu.jpg", "/images/category-sweets.jpg"],
    badge: "Classic",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 180, originalPrice: null },
      { size: "500g", price: 342, originalPrice: null },
      { size: "1kg", price: 648, originalPrice: null },
    ],
    description: "Coconut-rich Kobbari Vundalu (Coconut Balls) made with freshly grated coconut, jaggery, and cardamom. A simple yet irresistible traditional Andhra sweet.",
    ingredients: "Fresh coconut, Jaggery, Cardamom, Ghee",
    shelfLife: "10 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s16",
    name: "Kova Gajikayalu",
    slug: "kova-gajikayalu",
    price: 300,
    originalPrice: null,
    rating: 4.8,
    reviews: 86,
    image: "/images/product-kova-gajikayalu.jpg",
    images: ["/images/product-kova-gajikayalu.jpg", "/images/category-sweets.jpg"],
    badge: "Premium",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 300, originalPrice: null },
      { size: "500g", price: 570, originalPrice: null },
      { size: "1kg", price: 1080, originalPrice: null },
    ],
    description: "Crescent-shaped Kova Gajikayalu filled with rich kova (milk solid), dry fruits, and flavored with cardamom. A festive specialty that combines crispy pastry with creamy sweetness.",
    ingredients: "Maida, Kova, Dry fruits, Sugar, Cardamom, Ghee",
    shelfLife: "7 days",
    isVeg: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: "s17",
    name: "Madatha Kaja",
    slug: "madatha-kaja",
    price: 175,
    originalPrice: null,
    rating: 4.7,
    reviews: 91,
    image: "/images/product-madatha-kaja.jpg",
    images: ["/images/product-madatha-kaja.jpg", "/images/category-sweets.jpg"],
    badge: "Popular",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 175, originalPrice: null },
      { size: "500g", price: 332, originalPrice: null },
      { size: "1kg", price: 630, originalPrice: null },
    ],
    description: "Layered, flaky Madatha Kaja soaked in sugar syrup. A beloved Andhra sweet with multiple crispy layers that are crunchy on the outside and syrupy on the inside.",
    ingredients: "Maida, Sugar, Ghee, Cardamom",
    shelfLife: "15 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s18",
    name: "Milk Mysore Pak",
    slug: "milk-mysore-pak",
    price: 175,
    originalPrice: null,
    rating: 4.8,
    reviews: 112,
    image: "/images/product-milk-mysore-pak.jpg",
    images: ["/images/product-milk-mysore-pak.jpg", "/images/category-sweets.jpg"],
    badge: "Classic",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 175, originalPrice: null },
      { size: "500g", price: 332, originalPrice: null },
      { size: "1kg", price: 630, originalPrice: null },
    ],
    description: "Rich and melt-in-your-mouth Milk Mysore Pak made with besan, sugar, ghee, and milk. A South Indian classic sweet with a smooth, fudge-like texture.",
    ingredients: "Besan, Sugar, Ghee, Milk, Cardamom",
    shelfLife: "15 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s19",
    name: "Millet Gavvalu",
    slug: "millet-gavvalu",
    price: 175,
    originalPrice: null,
    rating: 4.6,
    reviews: 54,
    image: "/images/product-millet-gavvalu.jpg",
    images: ["/images/product-millet-gavvalu.jpg", "/images/category-sweets.jpg"],
    badge: "Healthy",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 175, originalPrice: null },
      { size: "500g", price: 332, originalPrice: null },
      { size: "1kg", price: 630, originalPrice: null },
    ],
    description: "Healthy Millet Gavvalu (shell-shaped sweet) made with millet flour and jaggery. A nutritious twist on the traditional gavvalu, packed with fiber and wholesome goodness.",
    ingredients: "Millet flour, Jaggery, Ghee, Sesame seeds, Cardamom",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: "s20",
    name: "Millet Laddu",
    slug: "millet-laddu",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 67,
    image: "/images/product-millet-laddu.jpg",
    images: ["/images/product-millet-laddu.jpg", "/images/category-sweets.jpg"],
    badge: "Healthy",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Nutritious Millet Laddu made with ragi, jowar, and bajra flours combined with jaggery and dry fruits. A healthy sweet alternative that tastes as good as it nourishes.",
    ingredients: "Millet flour, Jaggery, Dry fruits, Ghee, Cardamom",
    shelfLife: "20 days",
    isVeg: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: "s21",
    name: "Nuvvula Laddu",
    slug: "nuvvula-laddu",
    price: 150,
    originalPrice: null,
    rating: 4.7,
    reviews: 78,
    image: "/images/product-nuvvula-laddu.jpg",
    images: ["/images/product-nuvvula-laddu.jpg", "/images/category-sweets.jpg"],
    badge: "Traditional",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 150, originalPrice: null },
      { size: "500g", price: 285, originalPrice: null },
      { size: "1kg", price: 540, originalPrice: null },
    ],
    description: "Nutty Nuvvula (Sesame) Laddu made with roasted white sesame seeds and jaggery. Rich in calcium and iron, these laddus are both delicious and nutritious.",
    ingredients: "Sesame seeds, Jaggery, Cardamom, Dry ginger",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s22",
    name: "Pala Munjalu",
    slug: "pala-munjalu",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 48,
    image: "/images/product-pala-munjalu.jpg",
    images: ["/images/product-pala-munjalu.jpg", "/images/category-sweets.jpg"],
    badge: "Classic",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Soft Pala Munjalu made with milk, sugar, and maida. Dipped in milk syrup and mildly sweet, these are a gentle dessert loved across Andhra Pradesh.",
    ingredients: "Maida, Milk, Sugar, Cardamom, Ghee",
    shelfLife: "5 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s23",
    name: "Palakova Billalu",
    slug: "palakova-billalu",
    price: 325,
    originalPrice: null,
    rating: 4.9,
    reviews: 89,
    image: "/images/product-palakova-billalu.jpg",
    images: ["/images/product-palakova-billalu.jpg", "/images/category-sweets.jpg"],
    badge: "Premium",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 325, originalPrice: null },
      { size: "500g", price: 617, originalPrice: null },
      { size: "1kg", price: 1170, originalPrice: null },
    ],
    description: "Rich Palakova Billalu made with slow-reduced milk (palakova), sugar, and cardamom. Flat, fudge-like discs of concentrated milk sweetness. A premium Andhra delicacy.",
    ingredients: "Full cream milk, Sugar, Cardamom, Ghee",
    shelfLife: "7 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s24",
    name: "Peanut Laddus",
    slug: "peanut-laddus",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 81,
    image: "/images/product-peanut-laddus.jpg",
    images: ["/images/product-peanut-laddus.jpg", "/images/category-sweets.jpg"],
    badge: "Protein",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Crunchy Peanut Laddus made with roasted peanuts and jaggery. A protein-packed traditional sweet that is a favorite during Sankranti and Dussehra festivals.",
    ingredients: "Peanuts, Jaggery, Cardamom, Ghee",
    shelfLife: "20 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s25",
    name: "Poornam Boorelu",
    slug: "poornam-boorelu",
    price: 180,
    originalPrice: null,
    rating: 4.8,
    reviews: 96,
    image: "/images/product-poornam-boorelu.jpg",
    images: ["/images/product-poornam-boorelu.jpg", "/images/category-sweets.jpg"],
    badge: "Traditional",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 180, originalPrice: null },
      { size: "500g", price: 342, originalPrice: null },
      { size: "1kg", price: 648, originalPrice: null },
    ],
    description: "Round, golden Poornam Boorelu filled with sweet chana dal and coconut stuffing, coated in a rice flour batter and deep-fried. A Telangana festive classic.",
    ingredients: "Rice flour, Chana dal, Coconut, Jaggery, Cardamom, Oil",
    shelfLife: "3 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s26",
    name: "Pootharekulu",
    slug: "pootharekulu",
    price: 250,
    originalPrice: null,
    rating: 4.9,
    reviews: 143,
    image: "/images/product-pootharekulu.jpg",
    images: ["/images/product-pootharekulu.jpg", "/images/category-sweets.jpg"],
    badge: "Signature",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 250, originalPrice: null },
      { size: "500g", price: 475, originalPrice: null },
      { size: "1kg", price: 900, originalPrice: null },
    ],
    description: "Paper-thin Pootharekulu (Paper Sweet) from Atreyapuram. Ultra-thin rice starch sheets layered with ghee, powdered sugar, and dry fruits. A signature Andhra delicacy.",
    ingredients: "Rice starch, Powdered sugar, Ghee, Dry fruits, Cardamom",
    shelfLife: "15 days",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "s27",
    name: "Ragi Laddu",
    slug: "ragi-laddu",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 71,
    image: "/images/product-ragi-laddu.jpg",
    images: ["/images/product-ragi-laddu.jpg", "/images/category-sweets.jpg"],
    badge: "Healthy",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Nutritious Ragi (Finger Millet) Laddu made with roasted ragi flour, jaggery, and ghee. Rich in calcium and iron. A healthy sweet for kids and adults alike.",
    ingredients: "Ragi flour, Jaggery, Ghee, Cardamom, Dry fruits",
    shelfLife: "20 days",
    isVeg: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: "s28",
    name: "Sajja Burelu",
    slug: "sajja-burelu",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 55,
    image: "/images/product-sajja-burelu.jpg",
    images: ["/images/product-sajja-burelu.jpg", "/images/category-sweets.jpg"],
    badge: "Healthy",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Traditional Sajja (Pearl Millet) Burelu filled with jaggery and coconut. A healthy millet-based sweet dumpling that is steamed to perfection. A rural Telugu delicacy.",
    ingredients: "Pearl millet flour, Jaggery, Coconut, Cardamom",
    shelfLife: "3 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s29",
    name: "Sunnundalu",
    slug: "sunnundalu",
    price: 180,
    originalPrice: null,
    rating: 4.8,
    reviews: 156,
    image: "/images/product-sunnundalu.jpg",
    images: ["/images/product-sunnundalu.jpg", "/images/category-sweets.jpg"],
    badge: "Popular",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 180, originalPrice: null },
      { size: "500g", price: 342, originalPrice: null },
      { size: "1kg", price: 648, originalPrice: null },
    ],
    description: "Protein-rich Sunnundalu (Urad Dal Laddu) made with roasted black gram, pure ghee, and powdered sugar. A traditional Andhra sweet that melts in your mouth.",
    ingredients: "Urad Dal, Ghee, Powdered sugar, Cardamom, Dry ginger powder",
    shelfLife: "20 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "s30",
    name: "Till Ariselu",
    slug: "till-ariselu",
    price: 220,
    originalPrice: null,
    rating: 4.9,
    reviews: 124,
    image: "/images/product-till-ariselu.jpg",
    images: ["/images/product-till-ariselu.jpg", "/images/category-sweets.jpg"],
    badge: "Bestseller",
    category: "Sweets",
    weight: "250g",
    sizes: [
      { size: "250g", price: 220, originalPrice: null },
      { size: "500g", price: 418, originalPrice: null },
      { size: "1kg", price: 792, originalPrice: null },
    ],
    description: "Premium Till (Sesame) Ariselu made with rice flour, jaggery, and generous sesame seeds. Crispy on the outside, soft on the inside. A Sankranti festival essential.",
    ingredients: "Rice flour, Jaggery, Sesame seeds, Cardamom, Ghee",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },

  // =====================
  // VEG PICKLES (14 items from pickles category)
  // =====================
  {
    id: "vp1",
    name: "Allam Pachadi",
    slug: "allam-pachadi",
    price: 259,
    originalPrice: null,
    rating: 4.7,
    reviews: 63,
    image: "/images/product-allam-pachadi.jpg",
    images: ["/images/product-allam-pachadi.jpg", "/images/category-pickles.jpg"],
    badge: "Tangy",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Zesty Allam (Ginger) Pachadi made with fresh ginger, green chilies, tamarind, and a tempering of mustard and curry leaves. A tangy, spicy condiment that pairs perfectly with hot rice.",
    ingredients: "Ginger, Green chilies, Tamarind, Mustard seeds, Curry leaves, Sesame oil, Salt",
    shelfLife: "6 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp2",
    name: "Bellam Avakaya",
    slug: "bellam-avakaya",
    price: 259,
    originalPrice: null,
    rating: 4.8,
    reviews: 72,
    image: "/images/product-bellam-avakaya.jpg",
    images: ["/images/product-bellam-avakaya.jpg", "/images/category-pickles.jpg"],
    badge: "Sweet & Spicy",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Sweet and spicy Bellam (Jaggery) Avakaya made with raw mangoes, jaggery, chili powder, and sesame oil. A unique variation of the classic avakaya with a sweet twist.",
    ingredients: "Raw mangoes, Jaggery, Red chili powder, Mustard powder, Sesame oil, Fenugreek, Salt",
    shelfLife: "12 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp3",
    name: "Bellam Magaya",
    slug: "bellam-magaya",
    price: 259,
    originalPrice: null,
    rating: 4.7,
    reviews: 58,
    image: "/images/product-bellam-magaya.jpg",
    images: ["/images/product-bellam-magaya.jpg", "/images/category-pickles.jpg"],
    badge: "Sweet",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Traditional Bellam Magaya pickle made with raw mango and jaggery. A sweet-tangy delicacy from Andhra that tastes amazing with curd rice or as a side dish.",
    ingredients: "Raw mangoes, Jaggery, Mustard powder, Fenugreek, Sesame oil, Salt",
    shelfLife: "12 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp4",
    name: "Carrot Pickle",
    slug: "carrot-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.6,
    reviews: 47,
    image: "/images/product-carrot-pickle.jpg",
    images: ["/images/product-carrot-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Mild",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Crunchy Carrot Pickle made with fresh carrots, mustard, fenugreek, and a mild spice blend in sesame oil. A colorful, mildly spiced pickle loved by all ages.",
    ingredients: "Carrots, Red chili powder, Mustard powder, Fenugreek, Sesame oil, Salt",
    shelfLife: "6 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp5",
    name: "Chintakaya",
    slug: "chintakaya",
    price: 259,
    originalPrice: null,
    rating: 4.8,
    reviews: 81,
    image: "/images/product-chintakaya.jpg",
    images: ["/images/product-chintakaya.jpg", "/images/category-pickles.jpg"],
    badge: "Tangy",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Raw tamarind (Chintakaya) pickle made with tender green tamarind, red chili, and mustard in sesame oil. Intensely sour and spicy, a true Andhra favorite.",
    ingredients: "Raw tamarind, Red chili powder, Mustard powder, Fenugreek, Sesame oil, Salt",
    shelfLife: "12 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp6",
    name: "Dabbakaya",
    slug: "dabbakaya",
    price: 259,
    originalPrice: null,
    rating: 4.7,
    reviews: 52,
    image: "/images/product-dabbakaya.jpg",
    images: ["/images/product-dabbakaya.jpg", "/images/category-pickles.jpg"],
    badge: "Traditional",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Dabbakaya (Dried Mango) pickle made with sun-dried raw mango pieces, spiced and preserved in sesame oil. A shelf-stable delicacy with intense mango and spice flavors.",
    ingredients: "Dried raw mango, Red chili powder, Mustard powder, Fenugreek, Sesame oil, Salt",
    shelfLife: "12 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp7",
    name: "Dosakaya Pickle",
    slug: "dosakaya-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.7,
    reviews: 68,
    image: "/images/product-dosakaya-pickle.jpg",
    images: ["/images/product-dosakaya-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Classic",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Tangy Dosakaya (Yellow Cucumber) Pickle spiced with mustard, fenugreek, and red chili in sesame oil. A classic Andhra pickle with a unique sour-spicy taste.",
    ingredients: "Dosakaya, Red chili powder, Mustard powder, Fenugreek, Sesame oil, Salt",
    shelfLife: "6 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp8",
    name: "Gongura Pickle",
    slug: "gongura-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.9,
    reviews: 134,
    image: "/images/product-gongura.jpg",
    images: ["/images/product-gongura.jpg", "/images/category-pickles.jpg"],
    badge: "Signature",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "The crown jewel of Andhra pickles. Made with fresh gongura (sorrel) leaves, green chilies, garlic, and a tempering of mustard and fenugreek in sesame oil.",
    ingredients: "Gongura leaves, Green chilies, Garlic, Mustard seeds, Fenugreek, Sesame oil, Salt",
    shelfLife: "6 months",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "vp9",
    name: "Green Chilli Chinthakaya",
    slug: "green-chilli-chinthakaya",
    price: 259,
    originalPrice: null,
    rating: 4.7,
    reviews: 56,
    image: "/images/product-green-chilli-chinthakaya.jpg",
    images: ["/images/product-green-chilli-chinthakaya.jpg", "/images/category-pickles.jpg"],
    badge: "Spicy",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "A fiery combination of green chilies and raw tamarind (chinthakaya) in sesame oil. Double the heat, double the tang. For those who love their pickles extra spicy.",
    ingredients: "Green chilies, Raw tamarind, Mustard powder, Fenugreek, Sesame oil, Salt",
    shelfLife: "12 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp10",
    name: "Kakarakaya Pickle",
    slug: "kakarakaya-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.6,
    reviews: 44,
    image: "/images/product-kakarakaya-pickle.jpg",
    images: ["/images/product-kakarakaya-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Healthy",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Bitter gourd (Kakarakaya) pickle with a bold spice blend. The bitterness is balanced with tangy and spicy flavors. Believed to be great for health and digestion.",
    ingredients: "Bitter gourd, Red chili powder, Mustard powder, Fenugreek, Sesame oil, Salt",
    shelfLife: "6 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp11",
    name: "Kothimeera Pickle",
    slug: "kothimeera-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.7,
    reviews: 61,
    image: "/images/product-kothimeera-pickle.jpg",
    images: ["/images/product-kothimeera-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Aromatic",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Fresh Kothimeera (Coriander) Pickle bursting with herbaceous flavor. Made with fresh coriander, green chilies, garlic, and a touch of tamarind.",
    ingredients: "Coriander leaves, Green chilies, Garlic, Tamarind, Mustard seeds, Sesame oil, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: "vp12",
    name: "Lemon Pickle",
    slug: "lemon-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.7,
    reviews: 67,
    image: "/images/product-lemonpickle.jpg",
    images: ["/images/product-lemonpickle.jpg", "/images/category-pickles.jpg"],
    badge: "Tangy",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Zesty Lemon Pickle made with fresh lemons, turmeric, red chili, and mustard in sesame oil. Sun-cured for weeks for a deeply tangy and spicy flavor.",
    ingredients: "Lemons, Red chili powder, Turmeric, Mustard seeds, Sesame oil, Salt",
    shelfLife: "12 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp13",
    name: "Red Chilli Pickle",
    slug: "red-chilli-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.8,
    reviews: 73,
    image: "/images/product-red-chilli-pickle.jpg",
    images: ["/images/product-red-chilli-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Hot",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Fiery Red Chilli Pickle made with stuffed red chilies marinated in a spicy mustard and fenugreek blend. For the true spice lovers who want maximum heat.",
    ingredients: "Red chilies, Mustard powder, Fenugreek, Sesame oil, Salt",
    shelfLife: "12 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp14",
    name: "Tomato Pickle",
    slug: "tomato-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.6,
    reviews: 52,
    image: "/images/product-tomato-pickle.jpg",
    images: ["/images/product-tomato-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Mild",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Sweet and tangy Tomato Pickle made with ripe tomatoes, jaggery, and spices. A mild, slightly sweet pickle that is a favorite among kids and adults.",
    ingredients: "Tomatoes, Jaggery, Red chili powder, Mustard seeds, Fenugreek, Sesame oil, Salt",
    shelfLife: "6 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "vp15",
    name: "Avakaya Pickle",
    slug: "avakaya-pickle",
    price: 259,
    originalPrice: null,
    rating: 4.9,
    reviews: 89,
    image: "/images/product-avakaya.jpg",
    images: ["/images/product-avakaya.jpg", "/images/category-pickles.jpg"],
    badge: "Bestseller",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 259, originalPrice: null },
      { size: "500g", price: 492, originalPrice: null },
      { size: "1kg", price: 933, originalPrice: null },
    ],
    description: "Authentic Andhra Avakaya made with raw mangoes, mustard powder, red chili powder, and cold-pressed sesame oil. No preservatives, no artificial colors. Sun-dried to perfection.",
    ingredients: "Raw Mangoes, Mustard powder, Red chili powder, Sesame oil, Fenugreek seeds, Salt",
    shelfLife: "12 months",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },

  // =====================
  // NON-VEG PICKLES (7 items)
  // =====================
  {
    id: "nvp1",
    name: "Chicken Pickle",
    slug: "chicken-pickle",
    price: 389,
    originalPrice: null,
    rating: 4.8,
    reviews: 112,
    image: "/images/product-chicken-pickle.jpg",
    images: ["/images/product-chicken-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Popular",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 389, originalPrice: null },
      { size: "500g", price: 739, originalPrice: null },
      { size: "1kg", price: 1400, originalPrice: null },
    ],
    description: "Spicy Chicken Pickle made with boneless chicken pieces marinated in a fiery red chili and spice blend, cooked in sesame oil. A bold non-veg pickle that elevates any meal.",
    ingredients: "Chicken, Red chili powder, Garlic, Ginger, Mustard seeds, Fenugreek, Sesame oil, Salt",
    shelfLife: "3 months",
    isVeg: false,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "nvp2",
    name: "Fish Pickle",
    slug: "fish-pickle",
    price: 475,
    originalPrice: null,
    rating: 4.7,
    reviews: 68,
    image: "/images/product-fish-pickle.jpg",
    images: ["/images/product-fish-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Coastal",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 475, originalPrice: null },
      { size: "500g", price: 902, originalPrice: null },
      { size: "1kg", price: 1710, originalPrice: null },
    ],
    description: "Authentic coastal Fish Pickle made with fresh fish fillets deep-fried and marinated in a tangy, spicy masala with sesame oil. A delicacy from the Andhra coast.",
    ingredients: "Fish, Red chili powder, Garlic, Ginger, Tamarind, Mustard seeds, Sesame oil, Salt",
    shelfLife: "2 months",
    isVeg: false,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "nvp3",
    name: "Gongura Chicken Pickle",
    slug: "gongura-chicken-pickle",
    price: 439,
    originalPrice: null,
    rating: 4.9,
    reviews: 95,
    image: "/images/product-gongura-chicken-pickle.jpg",
    images: ["/images/product-gongura-chicken-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Signature",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 439, originalPrice: null },
      { size: "500g", price: 834, originalPrice: null },
      { size: "1kg", price: 1581, originalPrice: null },
    ],
    description: "A signature blend of tangy gongura leaves and tender chicken pieces pickled in a spicy masala. The best of Andhra veg and non-veg pickles combined in one jar.",
    ingredients: "Chicken, Gongura leaves, Red chili powder, Garlic, Mustard seeds, Sesame oil, Salt",
    shelfLife: "3 months",
    isVeg: false,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "nvp4",
    name: "Gongura Mutton Pickle",
    slug: "gongura-mutton-pickle",
    price: 624,
    originalPrice: null,
    rating: 4.9,
    reviews: 87,
    image: "/images/product-gongura-mutton-pickle.jpg",
    images: ["/images/product-gongura-mutton-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Premium",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 624, originalPrice: null },
      { size: "500g", price: 1185, originalPrice: null },
      { size: "1kg", price: 2246, originalPrice: null },
    ],
    description: "Premium Gongura Mutton Pickle combining tender mutton pieces with tangy gongura in a rich spice blend. A luxury pickle for the true connoisseur of Andhra non-veg flavors.",
    ingredients: "Mutton, Gongura leaves, Red chili powder, Garlic, Ginger, Mustard seeds, Sesame oil, Salt",
    shelfLife: "2 months",
    isVeg: false,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "nvp5",
    name: "Gongura Prawn Pickle",
    slug: "gongura-prawn-pickle",
    price: 525,
    originalPrice: null,
    rating: 4.8,
    reviews: 73,
    image: "/images/product-gongura-prawn-pickle.jpg",
    images: ["/images/product-gongura-prawn-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Coastal",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 525, originalPrice: null },
      { size: "500g", price: 997, originalPrice: null },
      { size: "1kg", price: 1890, originalPrice: null },
    ],
    description: "Succulent prawns paired with tangy gongura leaves in a spicy sesame oil pickle. The coastal-meets-Andhra combination that is absolutely irresistible.",
    ingredients: "Prawns, Gongura leaves, Red chili powder, Garlic, Ginger, Mustard seeds, Sesame oil, Salt",
    shelfLife: "2 months",
    isVeg: false,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "nvp6",
    name: "Mutton Pickle",
    slug: "mutton-pickle",
    price: 574,
    originalPrice: null,
    rating: 4.8,
    reviews: 91,
    image: "/images/product-mutton-pickle.jpg",
    images: ["/images/product-mutton-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Premium",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 574, originalPrice: null },
      { size: "500g", price: 1090, originalPrice: null },
      { size: "1kg", price: 2066, originalPrice: null },
    ],
    description: "Rich and hearty Mutton Pickle made with tender boneless mutton pieces slow-cooked in a spicy masala and preserved in sesame oil. A bold, meaty delicacy.",
    ingredients: "Mutton, Red chili powder, Garlic, Ginger, Fenugreek, Mustard seeds, Sesame oil, Salt",
    shelfLife: "2 months",
    isVeg: false,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "nvp7",
    name: "Prawns Pickle",
    slug: "prawns-pickle",
    price: 475,
    originalPrice: null,
    rating: 4.7,
    reviews: 65,
    image: "/images/product-prawns-pickle.jpg",
    images: ["/images/product-prawns-pickle.jpg", "/images/category-pickles.jpg"],
    badge: "Coastal",
    category: "Pickles",
    weight: "250g",
    sizes: [
      { size: "250g", price: 475, originalPrice: null },
      { size: "500g", price: 902, originalPrice: null },
      { size: "1kg", price: 1710, originalPrice: null },
    ],
    description: "Crispy Prawns Pickle made with fresh prawns marinated and cooked in a spicy Andhra masala blend with sesame oil. A coastal delight for seafood lovers.",
    ingredients: "Prawns, Red chili powder, Garlic, Ginger, Fenugreek, Mustard seeds, Sesame oil, Salt",
    shelfLife: "2 months",
    isVeg: false,
    isBestseller: false,
    isNew: false,
  },

  // =====================
  // SNACKS (13 items)
  // =====================
  {
    id: "sn1",
    name: "Atukulu Suduva",
    slug: "atukulu-suduva",
    price: 300,
    originalPrice: null,
    rating: 4.8,
    reviews: 85,
    image: "/images/product-atukulu-suduva.jpg",
    images: ["/images/product-atukulu-suduva.jpg", "/images/category-snacks.jpg"],
    badge: "Premium",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 300, originalPrice: null },
      { size: "500g", price: 570, originalPrice: null },
      { size: "1kg", price: 1080, originalPrice: null },
    ],
    description: "Crispy Atukulu Suduva (roasted flattened rice) seasoned with peanuts, curry leaves, green chilies, and traditional spices. A beloved Telugu snack for tea time.",
    ingredients: "Flattened rice (Poha), Peanuts, Curry leaves, Green chilies, Turmeric, Salt, Oil",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn2",
    name: "Chegodi",
    slug: "chegodi",
    price: 150,
    originalPrice: null,
    rating: 4.7,
    reviews: 76,
    image: "/images/product-chegodi.jpg",
    images: ["/images/product-chegodi.jpg", "/images/category-snacks.jpg"],
    badge: "Crispy",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 150, originalPrice: null },
      { size: "500g", price: 285, originalPrice: null },
      { size: "1kg", price: 540, originalPrice: null },
    ],
    description: "Traditional ring-shaped Chegodi made with rice flour and urad dal flour, deep-fried to a golden crunch. A classic Telugu snack for evening chai.",
    ingredients: "Rice flour, Urad dal flour, Sesame seeds, Cumin, Chili powder, Oil, Salt",
    shelfLife: "45 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn3",
    name: "Chittamma Spl Mixture",
    slug: "chittamma-spl-mixture",
    price: 160,
    originalPrice: null,
    rating: 4.8,
    reviews: 112,
    image: "/images/product-chittamma-mixture.jpg",
    images: ["/images/product-chittamma-mixture.jpg", "/images/category-snacks.jpg"],
    badge: "Bestseller",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Our signature Chittamma Special Mixture - a crunchy medley of flattened rice, roasted peanuts, cashews, curry leaves, and a secret blend of spices.",
    ingredients: "Poha, Peanuts, Cashews, Curry leaves, Chili powder, Turmeric, Oil, Salt",
    shelfLife: "45 days",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "sn4",
    name: "Chivda Mixture",
    slug: "chivda-mixture",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 68,
    image: "/images/product-chivda-mixture.jpg",
    images: ["/images/product-chivda-mixture.jpg", "/images/category-snacks.jpg"],
    badge: "Classic",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Traditional Chivda Mixture made with flattened rice, peanuts, and aromatic spices. Light and crunchy, an all-time favorite Indian tea-time snack.",
    ingredients: "Poha, Peanuts, Cashews, Raisins, Curry leaves, Turmeric, Oil, Salt",
    shelfLife: "45 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn5",
    name: "Green Chilli Chekkalu",
    slug: "green-chilli-chekkalu",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 74,
    image: "/images/product-green-chilli-chekkalu.jpg",
    images: ["/images/product-green-chilli-chekkalu.jpg", "/images/category-snacks.jpg"],
    badge: "Spicy",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Crispy rice crackers infused with bold green chili flavor. Handmade and sun-dried using traditional methods. A staple Andhra snack with a spicy kick.",
    ingredients: "Rice flour, Green chilies, Cumin seeds, Sesame seeds, Salt, Oil",
    shelfLife: "60 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn6",
    name: "Jonna Karapusa",
    slug: "jonna-karapusa",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 52,
    image: "/images/product-jonna-karapusa.jpg",
    images: ["/images/product-jonna-karapusa.jpg", "/images/category-snacks.jpg"],
    badge: "Traditional",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Traditional Jonna (jowar/sorghum) Karapusa - a millet-based crispy snack deep-fried to golden perfection. Rich in fiber and nutrients.",
    ingredients: "Jowar flour, Rice flour, Cumin seeds, Sesame seeds, Chili powder, Salt, Oil",
    shelfLife: "45 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn7",
    name: "Kaju Pakodi",
    slug: "kaju-pakodi",
    price: 250,
    originalPrice: null,
    rating: 4.8,
    reviews: 93,
    image: "/images/product-kaju-pakodi.jpg",
    images: ["/images/product-kaju-pakodi.jpg", "/images/category-snacks.jpg"],
    badge: "Premium",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 250, originalPrice: null },
      { size: "500g", price: 475, originalPrice: null },
      { size: "1kg", price: 900, originalPrice: null },
    ],
    description: "Premium Kaju Pakodi with generous whole cashews coated in a spiced besan batter and deep-fried to a golden crunch. Perfect for special occasions.",
    ingredients: "Cashews, Besan, Rice flour, Chili powder, Salt, Oil",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn8",
    name: "Karam Gavvalu",
    slug: "karam-gavvalu",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 86,
    image: "/images/product-karam-gavvalu.jpg",
    images: ["/images/product-karam-gavvalu.jpg", "/images/category-snacks.jpg"],
    badge: "Spicy",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Shell-shaped spicy Karam Gavvalu made with rice flour and a bold chili spice blend. Crunchy, fiery, and utterly addictive.",
    ingredients: "Rice flour, Red chili powder, Cumin seeds, Sesame seeds, Salt, Oil",
    shelfLife: "45 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn9",
    name: "Karapusa Sev",
    slug: "karapusa-sev",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 59,
    image: "/images/product-karapusa-sev.jpg",
    images: ["/images/product-karapusa-sev.jpg", "/images/category-snacks.jpg"],
    badge: "Classic",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Thin, crispy Karapusa Sev made with besan and rice flour, seasoned with aromatic spices. Light and crunchy, perfect as a standalone snack or chaat topping.",
    ingredients: "Besan, Rice flour, Red chili powder, Turmeric, Ajwain, Salt, Oil",
    shelfLife: "45 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn10",
    name: "Pappu Chekkalu",
    slug: "pappu-chekkalu",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 71,
    image: "/images/product-pappu-chekkalu.jpg",
    images: ["/images/product-pappu-chekkalu.jpg", "/images/category-snacks.jpg"],
    badge: "Traditional",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Sun-dried Pappu Chekkalu (lentil rice crackers) made with rice flour and urad dal, seasoned with cumin and green chilies. Full of authentic Telugu flavor.",
    ingredients: "Rice flour, Urad dal, Green chilies, Cumin seeds, Curry leaves, Salt, Oil",
    shelfLife: "60 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn11",
    name: "Ribbon Pakodi",
    slug: "ribbon-pakodi",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 82,
    image: "/images/product-ribbon-pakodi.jpg",
    images: ["/images/product-ribbon-pakodi.jpg", "/images/category-snacks.jpg"],
    badge: "Popular",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Thin ribbon-shaped crispy Pakodi made with besan and rice flour. Melt-in-your-mouth texture with a satisfying crunch. A festival favorite.",
    ingredients: "Besan, Rice flour, Butter, Red chili powder, Cumin, Salt, Oil",
    shelfLife: "45 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "sn12",
    name: "Sakinalu",
    slug: "sakinalu",
    price: 170,
    originalPrice: null,
    rating: 4.8,
    reviews: 95,
    image: "/images/product-sakinalu.jpg",
    images: ["/images/product-sakinalu.jpg", "/images/category-snacks.jpg"],
    badge: "Festive",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 170, originalPrice: null },
      { size: "500g", price: 323, originalPrice: null },
      { size: "1kg", price: 612, originalPrice: null },
    ],
    description: "Traditional Sakinalu - an iconic Telangana festive snack made by hand-rolling rice flour rings and deep-frying to golden perfection. A Sankranti must-have.",
    ingredients: "Rice flour, Sesame seeds, Cumin seeds, Salt, Oil",
    shelfLife: "30 days",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "sn13",
    name: "Spicy Boondi",
    slug: "spicy-boondi",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 64,
    image: "/images/product-spicy-boondi.jpg",
    images: ["/images/product-spicy-boondi.jpg", "/images/category-snacks.jpg"],
    badge: "Spicy",
    category: "Snacks",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Crunchy Spicy Boondi made with besan, seasoned with red chili powder, curry leaves, and hing. Perfect with chai or as a topping for raitas.",
    ingredients: "Besan, Red chili powder, Curry leaves, Hing, Salt, Oil",
    shelfLife: "45 days",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },

  // =====================
  // PODIS (10 items)
  // =====================
  {
    id: "p1",
    name: "Curry Leaves Podi",
    slug: "curry-leaves-podi",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 67,
    image: "/images/product-curry-leaves-podi.jpg",
    images: ["/images/product-curry-leaves-podi.jpg", "/images/category-podis.jpg"],
    badge: "Aromatic",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Fragrant Curry Leaves Podi made with dried curry leaves, urad dal, and red chilies. Rich in iron, this aromatic podi adds incredible depth to rice and ghee.",
    ingredients: "Curry leaves, Urad dal, Red chilies, Cumin, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "p2",
    name: "Dhaniyalu Podi",
    slug: "dhaniyalu-podi",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 54,
    image: "/images/product-dhaniyalu-podi.jpg",
    images: ["/images/product-dhaniyalu-podi.jpg", "/images/category-podis.jpg"],
    badge: "Mild",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Mildly spiced Dhaniyalu (Coriander) Podi made with roasted coriander seeds, urad dal, and red chilies. A gentle, aromatic podi perfect for those who prefer less heat.",
    ingredients: "Coriander seeds, Urad dal, Red chilies, Cumin, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "p3",
    name: "Flax Seed Podi",
    slug: "flax-seed-podi",
    price: 250,
    originalPrice: null,
    rating: 4.8,
    reviews: 62,
    image: "/images/product-flax-seed-podi.jpg",
    images: ["/images/product-flax-seed-podi.jpg", "/images/category-podis.jpg"],
    badge: "Healthy",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 250, originalPrice: null },
      { size: "500g", price: 475, originalPrice: null },
      { size: "1kg", price: 900, originalPrice: null },
    ],
    description: "Nutrient-rich Flax Seed Podi made with roasted flax seeds, red chilies, and garlic. Packed with Omega-3 fatty acids and fiber. A healthy superfood podi.",
    ingredients: "Flax seeds, Red chilies, Garlic, Cumin, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: "p4",
    name: "Kakarakaya Karam Podi",
    slug: "kakarakaya-karam-podi",
    price: 160,
    originalPrice: null,
    rating: 4.6,
    reviews: 48,
    image: "/images/product-kakarakaya-karam-podi.jpg",
    images: ["/images/product-kakarakaya-karam-podi.jpg", "/images/category-podis.jpg"],
    badge: "Unique",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Unique Kakarakaya (Bitter Gourd) Karam Podi made with dried bitter gourd, red chilies, and spices. A distinctive podi with health benefits that pairs well with hot rice.",
    ingredients: "Dried bitter gourd, Red chilies, Urad dal, Cumin, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "p5",
    name: "Kandi Podi",
    slug: "kandi-podi",
    price: 105,
    originalPrice: null,
    rating: 4.8,
    reviews: 58,
    image: "/images/product-kandipodi.jpg",
    images: ["/images/product-kandipodi.jpg", "/images/category-podis.jpg"],
    badge: "Essential",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 105, originalPrice: null },
      { size: "500g", price: 199, originalPrice: null },
      { size: "1kg", price: 378, originalPrice: null },
    ],
    description: "Classic Kandi Podi (Toor Dal Powder) made with roasted toor dal, red chilies, and cumin. The everyday podi that pairs beautifully with steaming hot rice and ghee.",
    ingredients: "Toor Dal, Red chilies, Cumin, Garlic, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "p6",
    name: "Kobbari Karam",
    slug: "kobbari-karam",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 71,
    image: "/images/product-kobbari-karam.jpg",
    images: ["/images/product-kobbari-karam.jpg", "/images/category-podis.jpg"],
    badge: "Classic",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Rich Kobbari (Coconut) Karam made with roasted coconut, sesame seeds, red chilies, and a hint of garlic. A creamy, nutty podi that elevates any meal.",
    ingredients: "Coconut, Sesame seeds, Red chilies, Garlic, Cumin, Salt",
    shelfLife: "2 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "p7",
    name: "Munagaku Karam",
    slug: "munagaku-karam",
    price: 180,
    originalPrice: null,
    rating: 4.8,
    reviews: 76,
    image: "/images/product-munagaku-karam.jpg",
    images: ["/images/product-munagaku-karam.jpg", "/images/category-podis.jpg"],
    badge: "Healthy",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 180, originalPrice: null },
      { size: "500g", price: 342, originalPrice: null },
      { size: "1kg", price: 648, originalPrice: null },
    ],
    description: "Nutrient-packed Munagaku (Drumstick Leaves/Moringa) Karam made with dried moringa leaves, red chilies, and garlic. A superfood podi rich in vitamins and minerals.",
    ingredients: "Moringa leaves, Red chilies, Garlic, Urad dal, Cumin, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "p8",
    name: "Nalla Karam",
    slug: "nalla-karam",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 65,
    image: "/images/product-nalla-karam.jpg",
    images: ["/images/product-nalla-karam.jpg", "/images/category-podis.jpg"],
    badge: "Spicy",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Dark and fiery Nalla (Black) Karam made with a special blend of roasted red chilies, sesame seeds, and spices. The quintessential Andhra spice powder for dosa and idli.",
    ingredients: "Red chilies, Sesame seeds, Urad dal, Garlic, Cumin, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "p9",
    name: "Nuvvula Karam",
    slug: "nuvvula-karam",
    price: 160,
    originalPrice: null,
    rating: 4.7,
    reviews: 63,
    image: "/images/product-nuvvulakaram.jpg",
    images: ["/images/product-nuvvulakaram.jpg", "/images/category-podis.jpg"],
    badge: "Aromatic",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 160, originalPrice: null },
      { size: "500g", price: 304, originalPrice: null },
      { size: "1kg", price: 576, originalPrice: null },
    ],
    description: "Nutty Nuvvula Karam (Sesame Spice Powder) made with roasted sesame seeds, red chilies, and garlic. Rich in calcium and iron. Mix with hot rice and ghee for an unforgettable meal.",
    ingredients: "Sesame seeds, Red chilies, Garlic, Cumin, Salt",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "p10",
    name: "Palli Karam",
    slug: "palli-karam",
    price: 163,
    originalPrice: null,
    rating: 4.8,
    reviews: 72,
    image: "/images/product-pallikaram.jpg",
    images: ["/images/product-pallikaram.jpg", "/images/category-podis.jpg"],
    badge: "Bestseller",
    category: "Podis",
    weight: "250g",
    sizes: [
      { size: "250g", price: 163, originalPrice: null },
      { size: "500g", price: 309, originalPrice: null },
      { size: "1kg", price: 587, originalPrice: null },
    ],
    description: "Fiery Palli Karam (Peanut Spice Powder) made with roasted peanuts, red chilies, garlic, and aromatic spices. The quintessential Andhra condiment for any rice dish.",
    ingredients: "Peanuts, Red chilies, Garlic, Cumin, Salt, Sesame oil",
    shelfLife: "3 months",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },

  // =====================
  // GIFT PACKS (2 items)
  // =====================
  {
    id: "gp1",
    name: "Festive Hamper",
    slug: "festive-hamper",
    price: 999,
    originalPrice: 1299,
    rating: 5.0,
    reviews: 43,
    image: "/images/product-festivehamper.jpg",
    images: ["/images/product-festivehamper.jpg", "/images/category-gifts.jpg"],
    badge: "Best Value",
    category: "Gift Packs",
    weight: "1.5 kg",
    sizes: [
      { size: "1.5 kg", price: 999, originalPrice: 1299 },
    ],
    description: "A beautifully curated festive hamper featuring our finest products: Boondi Laddus, Avakaya Pickle, Palli Karam, Sakinalu, and Ariselu. Elegantly packaged for gifting.",
    ingredients: "Assorted sweets, pickles, snacks, and spice powders",
    shelfLife: "15 days (sweets), 6+ months (pickles & podis)",
    isVeg: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "gp2",
    name: "Essentials Combo",
    slug: "essentials-combo",
    price: 599,
    originalPrice: 749,
    rating: 4.8,
    reviews: 37,
    image: "/images/product-essentials.jpg",
    images: ["/images/product-essentials.jpg", "/images/category-gifts.jpg"],
    badge: "Starter",
    category: "Gift Packs",
    weight: "1 kg",
    sizes: [
      { size: "1 kg", price: 599, originalPrice: 749 },
    ],
    description: "Start your Chittamma Ruchulu journey with this essentials combo. Includes Palli Karam, Kandi Podi, Avakaya Pickle, and Chegodi. The perfect introduction to authentic Andhra-Telangana flavors.",
    ingredients: "Assorted pickles, podis, and snacks",
    shelfLife: "3+ months",
    isVeg: true,
    isBestseller: false,
    isNew: true,
  },
]

export const categories = [
  "All",
  "Sweets",
  "Pickles",
  "Snacks",
  "Podis",
  "Gift Packs",
] as const

export type Category = (typeof categories)[number]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(category: Category): Product[] {
  if (category === "All") return products
  return products.filter((p) => p.category === category)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit)
}
